### ISSUE TITLE
Bug in Naive controller

### ISSUE THREAD

**Issue by dfbarrero** [ISG-UAH/r2p2#21]
Añadir la siguiente línea al principio del todo de la función de control (entre las líneas 53-54):

super(Naive_Controller, self).control(dst)

De lo contrario no se visualiza bien el trazado de rayos con los sensores.

**Comment by pedrosanchezr** [comment]
Suggested an implemetation based on decorators to implement the update of sensor angles in the control methods that need it.
As mentioned in the PR, if this is just overcomplicate it, I'll implement the super().control option.

In any case, I suggest to align the rest of Controllers to use super() or decorator instead of repeat the same line of code.

PR: #25

**Comment by pedrosanchezr** [comment]
New PR is #26 

I created the PR 25 from Develop and I'm merging all changes in develop so it contained other changes apart of the decorator

**Comment by pedrosanchezr** [comment]
Fixed after merging the PR #26
